Repository VoronDesign/VoronUsers, pull requests merged in 2020-12, with the labels that each got.

#157 added Galileo switchwire chain mount
  .gitignore
  printer_mods/README.md
  printer_mods/btp/Galileo_Switchwire_Chain_Mount/README.md
  printer_mods/btp/Galileo_Switchwire_Chain_Mount/switchwire chain.jpeg
  printer_mods/btp/Galileo_Switchwire_Chain_Mount/switchwire chain.stl
Labels: Action required by maintainers

#180 Afterburner connector cover for 42STH20-1004AS
  printer_mods/README.md
  printer_mods/hhammarstrand/afterburner_connector_cover_42STH20-1004AS/README.md
  printer_mods/hhammarstrand/afterburner_connector_cover_42STH20-1004AS/STEP/Voron_SwitchWire_Connector cover_LDO-42STH20-1004AS2.stp
  printer_mods/hhammarstrand/afterburner_connector_cover_42STH20-1004AS/STL/Voron_SwitchWire_Connector cover_LDO-42STH20-1004AS2.stl
  printer_mods/hhammarstrand/afterburner_connector_cover_42STH20-1004AS/compare.png
  printer_mods/hhammarstrand/afterburner_connector_cover_42STH20-1004AS/exodius_afterburner.jpg
Labels: CR: Readme

#177 Added V0 & 2.4 Skirt Buttons Mods
  printer_mods/README.md
  printer_mods/xbst_/V0_Electronic_Panel/Left_x2.stl
  printer_mods/xbst_/V0_Electronic_Panel/Panel.stl
  printer_mods/xbst_/V0_Electronic_Panel/README.md
  printer_mods/xbst_/V0_Electronic_Panel/Right_x2.stl
  printer_mods/xbst_/V0_Electronic_Panel/example.jpg
  printer_mods/xbst_/V0_M4_Mod/End_Plate.stl
  printer_mods/xbst_/V0_M4_Mod/Manual.pdf
  printer_mods/xbst_/V0_M4_Mod/Motor_Plate.stl
  printer_mods/xbst_/V0_M4_Mod/README.md
  printer_mods/xbst_/V0_M4_Mod/example.jpg
  printer_mods/xbst_/V0_Picam/Ball.stl
  printer_mods/xbst_/V0_Picam/Cam_A.STL
  printer_mods/xbst_/V0_Picam/Cam_B.STL
  printer_mods/xbst_/V0_Picam/README.md
  printer_mods/xbst_/V0_Picam/example.jpg
  printer_mods/xbst_/V0_Skirt_Buttons/Buttoned/A.stl
  printer_mods/xbst_/V0_Skirt_Buttons/Buttoned/B.stl
  printer_mods/xbst_/V0_Skirt_Buttons/Buttonless/A.stl
  printer_mods/xbst_/V0_Skirt_Buttons/Buttonless/B.stl
  printer_mods/xbst_/V0_Skirt_Buttons/Buttons.stl
  printer_mods/xbst_/V0_Skirt_Buttons/Buttons/CAD.f3d
  printer_mods/xbst_/V0_Skirt_Buttons/Front.stl
  printer_mods/xbst_/V0_Skirt_Buttons/Left.stl
  printer_mods/xbst_/V0_Skirt_Buttons/OLED_Cover/Buttons.stl
  printer_mods/xbst_/V0_Skirt_Buttons/OLED_Cover/Front.stl
  printer_mods/xbst_/V0_Skirt_Buttons/Pi.png
  printer_mods/xbst_/V0_Skirt_Buttons/README.md
  printer_mods/xbst_/V0_Skirt_Buttons/Right.stl
  printer_mods/xbst_/V0_Skirt_Buttons/Yeni Metin Belgesi.txt
  printer_mods/xbst_/V2.4_Skirt_Buttons/Buttons/CAD.f3d
Labels: CR: Printability

#187 Add various DIN brackets
  printer_mods/README.md
  printer_mods/aeresov/MeanWell_UHP_DIN_mount/CAD/MeanWell_UHP_DIN_mount.f3d
  printer_mods/aeresov/MeanWell_UHP_DIN_mount/Readme.md
  printer_mods/aeresov/MeanWell_UHP_DIN_mount/STLs/UHP_200_series.stl
  printer_mods/aeresov/MeanWell_UHP_DIN_mount/STLs/UHP_350_series.stl
  printer_mods/aeresov/MeanWell_UHP_DIN_mount/STLs/UHP_500_series.stl
  printer_mods/aeresov/MeanWell_UHP_DIN_mount/images/photo1.png
  printer_mods/aeresov/MeanWell_UHP_DIN_mount/images/photo2.png
  printer_mods/aeresov/MeanWell_UHP_DIN_mount/images/photo_bare_1.png
  printer_mods/aeresov/MeanWell_UHP_DIN_mount/images/photo_bare_2.png
  printer_mods/aeresov/MeanWell_UHP_DIN_mount/images/photo_railed_1.png
  printer_mods/aeresov/MeanWell_UHP_DIN_mount/images/photo_railed_2.png
  printer_mods/aeresov/Raspberry_Pi_DIN_mount/CAD/RPi_DIN_mount.f3d
  printer_mods/aeresov/Raspberry_Pi_DIN_mount/Readme.md
  printer_mods/aeresov/Raspberry_Pi_DIN_mount/STLs/RPi_DIN_mount.stl
  printer_mods/aeresov/Raspberry_Pi_DIN_mount/images/db.png
  printer_mods/aeresov/Raspberry_Pi_DIN_mount/images/photo_bare_1.png
  printer_mods/aeresov/Raspberry_Pi_DIN_mount/images/photo_bare_2.png
  printer_mods/aeresov/Raspberry_Pi_DIN_mount/images/photo_bare_3.png
  printer_mods/aeresov/Raspberry_Pi_DIN_mount/images/photo_railed.png
  printer_mods/aeresov/SKR_DIN_mount/CAD/SKR_DIN_mount.f3d
  printer_mods/aeresov/SKR_DIN_mount/Readme.md
  printer_mods/aeresov/SKR_DIN_mount/STLs/SKR_DIN_mount.stl
  printer_mods/aeresov/SKR_DIN_mount/images/db.png
  printer_mods/aeresov/SKR_DIN_mount/images/photo_bare_1.png
  printer_mods/aeresov/SKR_DIN_mount/images/photo_bare_2.png
  printer_mods/aeresov/SKR_DIN_mount/images/photo_bare_3.png
  printer_mods/aeresov/SKR_DIN_mount/images/photo_railed.png
  printer_mods/aeresov/TL_filament_sensor_bracket/CAD/TL_filament_sensor_bracket.f3d
  printer_mods/aeresov/TL_filament_sensor_bracket/Readme.md
  printer_mods/aeresov/TL_filament_sensor_bracket/STLs/TL_filament_sensor_bracket.stl
  printer_mods/aeresov/TL_filament_sensor_bracket/images/photo_bare_1.png
  printer_mods/aeresov/TL_filament_sensor_bracket/images/photo_bare_2.png
  printer_mods/aeresov/TL_filament_sensor_bracket/images/photo_railed_1.png
  printer_mods/aeresov/TL_filament_sensor_bracket/images/photo_railed_2.png
  printer_mods/aeresov/TL_filament_sensor_bracket/images/render0.png
  printer_mods/aeresov/TL_filament_sensor_bracket/images/render1.png
  printer_mods/aeresov/cable_tie_DIN_mount/CAD/cable_tie_DIN_mount.f3d
  printer_mods/aeresov/cable_tie_DIN_mount/Readme.md
  printer_mods/aeresov/cable_tie_DIN_mount/STLs/cable_tie_DIN_mount.stl
  printer_mods/aeresov/cable_tie_DIN_mount/images/db.png
  printer_mods/aeresov/cable_tie_DIN_mount/images/photo_bare.png
  printer_mods/aeresov/cable_tie_DIN_mount/images/photo_railed.png
Labels: CR: Printability

#190 Switchwire Lightbar mod v1
  printer_mods/KenadyDwag44/sw_lightbar/README.md
  printer_mods/KenadyDwag44/sw_lightbar/SW_lightbar_led_holder_modified_x1.stl
  printer_mods/KenadyDwag44/sw_lightbar/SW_lightbar_left_mount_x1.stl
  printer_mods/KenadyDwag44/sw_lightbar/SW_lightbar_right_mount_x1.stl
  printer_mods/KenadyDwag44/sw_lightbar/photos/IMG_2278.jpg
  printer_mods/README.md
Labels: CR: Readme, Duplicate Mod

#205 V0 power wagos
  printer_mods/README.md
  printer_mods/deepfriedheroin/v0_power_wagos/cad/v0_3x3_wago v2.f3d
  printer_mods/deepfriedheroin/v0_power_wagos/cad/v0_3x3_wago v2.step
  printer_mods/deepfriedheroin/v0_power_wagos/images/mains_wago_v0_1.jpeg
  printer_mods/deepfriedheroin/v0_power_wagos/images/mains_wago_v0_2.jpeg
  printer_mods/deepfriedheroin/v0_power_wagos/images/mains_wago_v0_3.png
  printer_mods/deepfriedheroin/v0_power_wagos/readme.md
  printer_mods/deepfriedheroin/v0_power_wagos/stl/v0_3x3_wago v2.stl
Labels: CR: Files and Folders

#183 Voron V0 Zipties Hooks and Bowden "Fence"
  printer_mods/BlueBear/Bowden_Fence/1515_SnapIn_LDO.step
  printer_mods/BlueBear/Bowden_Fence/1515_SnapIn_LDO.stl
  printer_mods/BlueBear/Bowden_Fence/1515_SnapIn_Makerbeam.step
  printer_mods/BlueBear/Bowden_Fence/1515_SnapIn_Makerbeam.stl
  printer_mods/BlueBear/Bowden_Fence/BowdenFence.step
  printer_mods/BlueBear/Bowden_Fence/BowdenFence.stl
  printer_mods/BlueBear/Bowden_Fence/README.md
  printer_mods/BlueBear/Bowden_Fence/images/image01.jpg
  printer_mods/BlueBear/Bowden_Fence/images/image02.jpg
  printer_mods/BlueBear/Bowden_Fence/images/image03.jpg
  printer_mods/BlueBear/Ziptie_Mount/1515_SnapIn_ZipTie_LDO.step
  printer_mods/BlueBear/Ziptie_Mount/1515_SnapIn_ZipTie_LDO.stl
  printer_mods/BlueBear/Ziptie_Mount/1515_SnapIn_ZipTie_Makerbeam.step
  printer_mods/BlueBear/Ziptie_Mount/1515_SnapIn_ZipTie_Makerbeam.stl
  printer_mods/BlueBear/Ziptie_Mount/README.md
  printer_mods/BlueBear/Ziptie_Mount/images/image01.jpg
  printer_mods/BlueBear/Ziptie_Mount/images/image02.jpg
  printer_mods/BlueBear/Ziptie_Mount/images/image03.jpg
  printer_mods/README.md
Labels: Pending Question
