Repository VoronDesign/VoronUsers, pull requests merged in 2021-12, with the labels that each got.

#535 MiniAB Pinda Probe Mount
  printer_mods/MrDespair/MiniAB_Pinda/CAD/CAD1.png
  printer_mods/MrDespair/MiniAB_Pinda/CAD/Cowling_Dragon_v3.step
  printer_mods/MrDespair/MiniAB_Pinda/CAD/cad2.png
  printer_mods/MrDespair/MiniAB_Pinda/CAD/cad3.png
  printer_mods/MrDespair/MiniAB_Pinda/CAD/readme.md
  printer_mods/MrDespair/MiniAB_Pinda/Images/CAD1.png
  printer_mods/MrDespair/MiniAB_Pinda/Images/ProbeInAction.jpg
  printer_mods/MrDespair/MiniAB_Pinda/Images/cad2.png
  printer_mods/MrDespair/MiniAB_Pinda/Images/cad3.png
  printer_mods/MrDespair/MiniAB_Pinda/Images/readme.md
  printer_mods/MrDespair/MiniAB_Pinda/STLs/Cowling_Dragon_v3.stl
  printer_mods/MrDespair/MiniAB_Pinda/STLs/readme.md
  printer_mods/MrDespair/MiniAB_Pinda/readme.md
  printer_mods/README.md
Labels: CR: STL Issues

#511 CableGator
  printer_mods/Kyleisah/CableGator/F3D/CableGator.f3d
  printer_mods/Kyleisah/CableGator/Images/Assembly1.png
  printer_mods/Kyleisah/CableGator/Images/Assembly2.png
  printer_mods/Kyleisah/CableGator/Images/Assembly3.png
  printer_mods/Kyleisah/CableGator/Images/Assembly4.png
  printer_mods/Kyleisah/CableGator/Images/CHOMP.png
  printer_mods/Kyleisah/CableGator/Images/LayingWires.png
  printer_mods/Kyleisah/CableGator/Images/StylishView.png
  printer_mods/Kyleisah/CableGator/README.md
  printer_mods/Kyleisah/CableGator/STLs/Voron-CableGator-Lower-Jaw.stl
  printer_mods/Kyleisah/CableGator/STLs/Voron-CableGator-Upper-Jaw.stl
  printer_mods/README.md
Labels: CR: Readme

#537 Kirigami bed front
  printer_mods/Kosh42EFG/kirigami_bed_front/CAD/Front_Bed_Mount.f3d
  printer_mods/Kosh42EFG/kirigami_bed_front/README.md
  printer_mods/Kosh42EFG/kirigami_bed_front/STLs/Front_Bed_Mount_x1.stl
  printer_mods/README.md
Labels: CR: Files and Folders, CR: Printability

#518 1515ledmod
  printer_mods/Jon/1515_led_mount/IMG/colors.jpg
  printer_mods/Jon/1515_led_mount/IMG/led_strip.jpg
  printer_mods/Jon/1515_led_mount/IMG/print_finish.gif
  printer_mods/Jon/1515_led_mount/IMG/wiring.jpg
  printer_mods/Jon/1515_led_mount/README.md
  printer_mods/Jon/1515_led_mount/STL/1515LedDiffuser.16mm.stl
  printer_mods/Jon/1515_led_mount/STL/1515LedDiffuser.17mm.stl
  printer_mods/README.md
Labels: CR: Readme, Action required by maintainers

#528 Tridentified V2.4 Power Inlet - Side mounted power inlet like Trident
  printer_mods/README.md
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/250/PlugSkirt_250_Filtered.stl
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/250/PlugSkirt_250_adamstech.stl
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/250/PlugSkirt_250_single.stl
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/250/RightSkirt_250.stl
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/300/FillSkirt.stl
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/300/PlugSkirt_300_Filtered.stl
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/300/PlugSkirt_300_adamstech.stl
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/300/PlugSkirt_300_single.stl
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/350/FillSkirt.stl
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/350/PlugSkirt_350_Filtered.stl
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/350/PlugSkirt_350_adamstech.stl
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/350/PlugSkirt_350_single.stl
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/images/Model.png
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/images/db.png
  printer_mods/edwardyeeks/Tridentified_V2.4_Power_Inlet/readme.md
Labels: CR: Readme

#532 DS18B20 sensor mount for the v0.1
  printer_mods/README.md
  printer_mods/antoinecellerier/ds18b20-sensor-mount/CAD/DS18B20-sensor-mount.f3d
  printer_mods/antoinecellerier/ds18b20-sensor-mount/Images/CAD_1.jpg
  printer_mods/antoinecellerier/ds18b20-sensor-mount/Images/CAD_2.jpg
  printer_mods/antoinecellerier/ds18b20-sensor-mount/Images/CAD_3.jpg
  printer_mods/antoinecellerier/ds18b20-sensor-mount/Images/CAD_4.jpg
  printer_mods/antoinecellerier/ds18b20-sensor-mount/Images/PIC_1.jpg
  printer_mods/antoinecellerier/ds18b20-sensor-mount/Images/PIC_2.jpg
  printer_mods/antoinecellerier/ds18b20-sensor-mount/Images/PIC_3.jpg
  printer_mods/antoinecellerier/ds18b20-sensor-mount/Images/PIC_4.jpg
  printer_mods/antoinecellerier/ds18b20-sensor-mount/README.md
  printer_mods/antoinecellerier/ds18b20-sensor-mount/STL/DS18B20-sensor-mount.stl
Labels: CR: Readme

#502 V2.4 Door Hinge M3 as shaft, 3mm panel, 180deg opening freedom
  printer_mods/README.md
  printer_mods/quattroerik/front_door_m3_180_deg_3mm/Assembly.png
  printer_mods/quattroerik/front_door_m3_180_deg_3mm/Front_Door_Mod.f3d
  printer_mods/quattroerik/front_door_m3_180_deg_3mm/README.md
  printer_mods/quattroerik/front_door_m3_180_deg_3mm/door_hinge_new.png
  printer_mods/quattroerik/front_door_m3_180_deg_3mm/hinge_left_x2.stl
  printer_mods/quattroerik/front_door_m3_180_deg_3mm/hinge_mount_x4.stl
  printer_mods/quattroerik/front_door_m3_180_deg_3mm/hinge_right_x2.stl
  printer_mods/quattroerik/front_door_m3_180_deg_3mm/latch_x2.stl
Labels: Ready to Merge

#548 Add DerekBackus mod section with skirt mods
  printer_mods/DerekBackus/LED_Holder/Images/LED_Holder_ISO.png
  printer_mods/DerekBackus/LED_Holder/Images/LED_Holder_Picture.jpg
  printer_mods/DerekBackus/LED_Holder/Images/LED_Holder_Side_View.png
  printer_mods/DerekBackus/LED_Holder/Images/LED_Strip_Example.jpg
  printer_mods/DerekBackus/LED_Holder/LED_Holder_340mm.ipt
  printer_mods/DerekBackus/LED_Holder/LED_Holder_340mm.stl
  printer_mods/DerekBackus/LED_Holder/README.md
  printer_mods/DerekBackus/README.md
  printer_mods/DerekBackus/Right_Skirt_Switch/Filtered_Main_Skirt.stl
  printer_mods/DerekBackus/Right_Skirt_Switch/Images/Filter_Front_View.png
  printer_mods/DerekBackus/Right_Skirt_Switch/Images/Filter_ISO_View.png
  printer_mods/DerekBackus/Right_Skirt_Switch/Images/Front_View.png
  printer_mods/DerekBackus/Right_Skirt_Switch/Images/ISO_View.png
  printer_mods/DerekBackus/Right_Skirt_Switch/README.md
  printer_mods/DerekBackus/Right_Skirt_Switch/Side_Skirt_A_Switch.stl
  printer_mods/DerekBackus/Right_Skirt_Switch/cad/Filtered_Main_Skirt.stp
  printer_mods/DerekBackus/Right_Skirt_Switch/cad/Side_Skirt_A_Switch.stp
  printer_mods/README.md
Labels: Ready to Merge

#554 Add Monster8 v1.0_003 config file
  firmware_configurations/README.md
  firmware_configurations/klipper/RealDeuce/MKS-Makerbase/Monster8_v1.0_003/README.md
  firmware_configurations/klipper/RealDeuce/MKS-Makerbase/Monster8_v1.0_003/Voron2_Monster8_Config.cfg
  firmware_configurations/klipper/RealDeuce/MKS-Makerbase/Monster8_v1.0_003/images/v2-monster8-initial-preparation.jpg
  firmware_configurations/klipper/RealDeuce/MKS-Makerbase/Monster8_v1.0_003/images/v2_monster8_wiring.png
Labels: Ready to Merge

#558 Adding a new mod, Z Belt Clip
  printer_mods/ChenTheDesignMaker/Z_Belt_Clip/README.md
  printer_mods/ChenTheDesignMaker/Z_Belt_Clip/imgs/IMG_3018.jpg
  printer_mods/ChenTheDesignMaker/Z_Belt_Clip/imgs/IMG_3019.jpg
  printer_mods/ChenTheDesignMaker/Z_Belt_Clip/imgs/IMG_3020.jpg
  printer_mods/ChenTheDesignMaker/Z_Belt_Clip/z_belt_clipX4.stl
  printer_mods/README.md
Labels: Ready to Merge

#555 Added drop-in replacement, code optimization, improved setup & assemb…
  printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/CAD/Quickdraw_for_VSW.step
  printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/Initial_Setup_Guide/README.md
  printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/Klipper_Macros/README.md
  printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/Klipper_Macros/dock_macros.cfg
  printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/Pictures/quickdraw_SW_probe.png
  printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/Pictures/quickdraw_SW_remix.png
  printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/README.md
  printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/STLs/Dock_Arm_Endblock_Quickdraw_VSW.stl
  printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/STLs/Dock_Arm_Quickdraw_VSW.stl
  printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/STLs/Dock_Quickdraw_VSW_adjustable.stl
  printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/STLs/Drop-In-Probe-Attachment_Quickdraw_VSW.stl
  printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/STLs/KeyBak_Mount_Z_endstop.stl
  printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/STLs/README.md
Labels: Ready to Merge
