Repository VoronDesign/VoronUsers, pull requests merged in 2022-04, with the labels that each got.

#664 Adding MKS Mosfet Mount
  printer_mods/README.md
  printer_mods/mikepthomas/MKS_Mosfet_Mount/CAD/MKS_Mosfet_Mount.step
  printer_mods/mikepthomas/MKS_Mosfet_Mount/Images/MKS_Mosfet.png
  printer_mods/mikepthomas/MKS_Mosfet_Mount/Images/MKS_Mosfet_Mount.png
  printer_mods/mikepthomas/MKS_Mosfet_Mount/README.md
  printer_mods/mikepthomas/MKS_Mosfet_Mount/STL/MKS_Mosfet_Mount.stl
Labels: Ready to Merge

#675 firmware_configurations/klipper: Fysetc S6 V2.1
  firmware_configurations/README.md
  firmware_configurations/klipper/clee/fysetc_s6/fysetc_s6_v2.1_pin_aliases.cfg
  firmware_configurations/klipper/clee/fysetc_s6/v0-fysetc_s6_v2.1.cfg
Labels: CR: Readme, Pending Question

#671 add V0 No-Drop Nuts for door latches
  printer_mods/zruncho/V0_No_Drop_Nuts/README.md
  printer_mods/zruncho/V0_No_Drop_Nuts/cad/NoDropNut_Door_Latch_x2.step
  printer_mods/zruncho/V0_No_Drop_Nuts/stl/NoDropNut_Door_Latch_x2.stl
Labels: Ready to Merge

#665 C92X_PsycHoShafts_Mount
  printer_mods/PsychoShaft/C92X_PsycHoShafts_Mount/CAD/Voron_C92X_Camera_Complete.f3d
  printer_mods/PsychoShaft/C92X_PsycHoShafts_Mount/CAD/Voron_C92X_Camera_Complete.step
  printer_mods/PsychoShaft/C92X_PsycHoShafts_Mount/Images/Camera_complete.jpg
  printer_mods/PsychoShaft/C92X_PsycHoShafts_Mount/Images/Camera_fit_on_profile.jpg
  printer_mods/PsychoShaft/C92X_PsycHoShafts_Mount/Images/Camera_front_view.jpg
  printer_mods/PsychoShaft/C92X_PsycHoShafts_Mount/Images/Camera_hinge_design.jpg
  printer_mods/PsychoShaft/C92X_PsycHoShafts_Mount/README.MD
  printer_mods/PsychoShaft/C92X_PsycHoShafts_Mount/STL/C92X_Camera_Bracket.stl
  printer_mods/PsychoShaft/C92X_PsycHoShafts_Mount/STL/C92X_Extrusion_Bracket_No_Support_Required.stl
  printer_mods/PsychoShaft/C92X_PsycHoShafts_Mount/STL/C92X_Spacer_Arm.stl
  printer_mods/README.md
Labels: Ready to Merge

#610 Lgx lite toolhead pcb mount
  printer_mods/Fiction/LGX_Lite_toolhead_PCB_mount/Images/github_download.png
  printer_mods/Fiction/LGX_Lite_toolhead_PCB_mount/README.md
Labels: Ready to Merge

#577 In-Line Filament Dust Scrubber
  printer_mods/LJ/Scrubby/README.md
  printer_mods/LJ/Scrubby/Scrubby.SLDPRT
  printer_mods/LJ/Scrubby/Scrubby.STEP
  printer_mods/LJ/Scrubby/Scrubby.stl
  printer_mods/LJ/Scrubby/images/back.PNG
  printer_mods/LJ/Scrubby/images/built.JPG
  printer_mods/LJ/Scrubby/images/front.PNG
  printer_mods/LJ/Scrubby/images/irl.JPG
  printer_mods/README.md
Labels: Ready to Merge

#661 Trident bed fans
  printer_mods/CannedBass/Trident_Bed_Fans/CAD/5015_Bed_Fan_Mount_Trident.f3d
  printer_mods/CannedBass/Trident_Bed_Fans/CAD/5015_Bed_Fan_Mount_Trident.step
  printer_mods/CannedBass/Trident_Bed_Fans/Images/trident_bed_fans.jpeg
  printer_mods/CannedBass/Trident_Bed_Fans/README.md
  printer_mods/CannedBass/Trident_Bed_Fans/STL/Mounting_Plate.stl
  printer_mods/README.md
Labels: Ready to Merge

#622 Mathematical potato
  printer_mods/MathematicalPotato/v0.1_belted_z_drive/STL/Kirigami_Bed_Mount/V0-ZBelt-KirigamiBed_belt_mount.stl
  printer_mods/MathematicalPotato/v0.1_belted_z_drive/STL/Kirigami_Bed_Mount/V0-ZBelt-KirigamiBed_body.stl
Labels: CR: Git issues

#568 Bracket for Octopus (PRO) Boards
  printer_mods/DaStivi/the_Cephalopods_limb/README.md
  printer_mods/DaStivi/the_Cephalopods_limb/STL/Octopus_limbs_bracket.stl
  printer_mods/DaStivi/the_Cephalopods_limb/STL/Simple_Octopus_Bracket_v2.stl
  printer_mods/DaStivi/the_Cephalopods_limb/img/IMG-20210610-WA0001.jpg
  printer_mods/DaStivi/the_Cephalopods_limb/img/STL.jpg
  printer_mods/DaStivi/the_Cephalopods_limb/img/octopus.svg
  printer_mods/DaStivi/the_Cephalopods_limb/img/octopus_inverted.svg
  printer_mods/DaStivi/the_Cephalopods_limb/img/simple_bracket_STL.jpg
  printer_mods/README.md
Labels: Ready to Merge

#677 Add PITFT50 45-degree mount
  printer_mods/CannedBass/PITFT50_45_degree_mount/CAD/PITFT50_45_degree_mount.f3d
  printer_mods/CannedBass/PITFT50_45_degree_mount/CAD/PITFT50_45_degree_mount.step
  printer_mods/CannedBass/PITFT50_45_degree_mount/Images/side-view.jpeg
  printer_mods/CannedBass/PITFT50_45_degree_mount/README.md
  printer_mods/CannedBass/PITFT50_45_degree_mount/STL/PITFT50_45_degree_mount.stl
  printer_mods/README.md
Labels: CR: Readme

#611 Add my mods to user mods directory
  printer_mods/Hobson318/Belt_Tension_Wrench/Belt_Tension_Wrench.stl
  printer_mods/Hobson318/Belt_Tension_Wrench/Images/Tool.jpg
  printer_mods/Hobson318/Belt_Tension_Wrench/Images/Tool_2.jpg
  printer_mods/Hobson318/Belt_Tension_Wrench/README.md
  printer_mods/Hobson318/Belt_Tension_Wrench/belt_wrench_v4.step
  printer_mods/Hobson318/Klipper_Expander_Mount/Images/Mount_Side.jpg
  printer_mods/Hobson318/Klipper_Expander_Mount/Images/Mount_Top.jpg
  printer_mods/Hobson318/Klipper_Expander_Mount/Klipper_Expander_Mount.stl
  printer_mods/Hobson318/Klipper_Expander_Mount/Klipper_Expander_Mount_with_Mounting_Holes.stl
  printer_mods/Hobson318/Klipper_Expander_Mount/README.md
  printer_mods/Hobson318/Klipper_Expander_Mount/STM32_Klipper_Expander_No_Holes_v2.step
  printer_mods/Hobson318/Klipper_Expander_Mount/STM32_Klipper_Expander_v5.step
  printer_mods/README.md
Labels: Ready to Merge

#609 Belt tension helper for V0.1
  printer_mods/MSA/V0-Belt-tension-helper/CAD/Belttool.f3d
  printer_mods/MSA/V0-Belt-tension-helper/CAD/readme.md
  printer_mods/MSA/V0-Belt-tension-helper/Images/Belttool-img1.jpg
  printer_mods/MSA/V0-Belt-tension-helper/Images/Belttool-img1text.jpg
  printer_mods/MSA/V0-Belt-tension-helper/Images/Belttool-img1text2.jpg
  printer_mods/MSA/V0-Belt-tension-helper/Images/Belttool-img2.jpg
  printer_mods/MSA/V0-Belt-tension-helper/Images/Belttool-img2text.jpg
  printer_mods/MSA/V0-Belt-tension-helper/Images/Belttool-img3.jpg
  printer_mods/MSA/V0-Belt-tension-helper/Images/Belttool-img3text.jpg
  printer_mods/MSA/V0-Belt-tension-helper/Images/Belttool-img3text2.jpg
  printer_mods/MSA/V0-Belt-tension-helper/Images/Belttool-img4.jpg
  printer_mods/MSA/V0-Belt-tension-helper/Images/Belttool-img5.jpg
  printer_mods/MSA/V0-Belt-tension-helper/Images/Belttool-img5text.jpg
  printer_mods/MSA/V0-Belt-tension-helper/Images/Belttool-img6.jpg
  printer_mods/MSA/V0-Belt-tension-helper/Images/Tension_tool_drawing.PNG
  printer_mods/MSA/V0-Belt-tension-helper/Images/Tension_tool_slicing.PNG
  printer_mods/MSA/V0-Belt-tension-helper/Images/readme.md
  printer_mods/MSA/V0-Belt-tension-helper/STL/belttool-btm_v2.stl
  printer_mods/MSA/V0-Belt-tension-helper/STL/belttool-top_v2.stl
  printer_mods/MSA/V0-Belt-tension-helper/STL/readme.md
  printer_mods/MSA/V0-Belt-tension-helper/readme.md
  printer_mods/MSA/readme.md
  printer_mods/README.md
Labels: Ready to Merge

#620 V2.4-Trident-Spool-Holders
  printer_mods/README.md
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/Images/1.png
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/Images/2.png
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/Images/3.png
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/Images/4.png
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/Images/5.png
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/Images/6.png
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/README.md
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/STL/BB__spool_arm_left.stl
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/STL/BB__spool_arm_right.stl
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/STL/BB__spool_core.stl
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/STL/Classic__spool_arm_left.stl
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/STL/Classic__spool_arm_right.stl
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/STL/Classic__spool_holder.stl
Labels: CR: Readme

#576 6mm slot cover
  printer_mods/README.md
  printer_mods/filotto78/6mm_slot_cover/CAD/2020_cover_one_side.f3d
  printer_mods/filotto78/6mm_slot_cover/CAD/2020_cover_simmetric.f3d
  printer_mods/filotto78/6mm_slot_cover/README.md
  printer_mods/filotto78/6mm_slot_cover/STL/slot_cover.stl
  printer_mods/filotto78/6mm_slot_cover/STL/slot_cover_one_side.stl
  printer_mods/filotto78/6mm_slot_cover/images/IMG_3238.jpeg
  printer_mods/filotto78/6mm_slot_cover/images/IMG_3239.jpeg
  printer_mods/filotto78/6mm_slot_cover/images/one_side.jpg
  printer_mods/filotto78/6mm_slot_cover/images/symmetric.jpg
Labels: Ready to Merge

#680 firmware_configurations/klipper: MKS Eagle V1.0
  firmware_configurations/README.md
  firmware_configurations/klipper/clee/mks_eagle/README.md
  firmware_configurations/klipper/clee/mks_eagle/mks_eagle_v1.0-make_menuconfig.png
  firmware_configurations/klipper/clee/mks_eagle/mks_eagle_v1.0_pin_aliases.cfg
  firmware_configurations/klipper/clee/mks_eagle/v0-mks_eagle_v1.0.cfg
Labels: CR: Readme

#679 Added new STLs for spool holder variations
  printer_mods/elcrni/README
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/README.md
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/Readme
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/STL/BB__spool_arm_left__without_panel_pin.stl
  printer_mods/elcrni/V2.4-Trident-Spool-Holders/STL/Classic__spool_arm_left__without_panel_pin.stl
Labels: CR: Readme

#678 Johanncc
  printer_mods/README.md
  printer_mods/johanncc/Raspberry_Pi_Camera_Mount/CAD/Raspberry_Pi_Camera_Mount.step
  printer_mods/johanncc/Raspberry_Pi_Camera_Mount/Images/img01.jpg
  printer_mods/johanncc/Raspberry_Pi_Camera_Mount/Images/img02.png
  printer_mods/johanncc/Raspberry_Pi_Camera_Mount/Images/img03.jpg
  printer_mods/johanncc/Raspberry_Pi_Camera_Mount/Images/img04.jpg
  printer_mods/johanncc/Raspberry_Pi_Camera_Mount/Images/img05.jpg
  printer_mods/johanncc/Raspberry_Pi_Camera_Mount/Images/img06.jpg
  printer_mods/johanncc/Raspberry_Pi_Camera_Mount/README.md
  printer_mods/johanncc/Raspberry_Pi_Camera_Mount/STL/Raspberry_Pi_Camera_Mount.stl
Labels: Ready to Merge

#695 WagoMounts mod
  printer_mods/LoganFraser/README.md
  printer_mods/LoganFraser/WagoMounts/CAD/Wago_221-41x_Extrusion_&_Thin_Din_Mount.f3d
  printer_mods/LoganFraser/WagoMounts/CAD/Wago_221-41x_Extrusion_&_Thin_Din_Mount.step
  printer_mods/LoganFraser/WagoMounts/CAD/Wago_3x_221-41x_Angled_Din_Rail_Mount.f3d
  printer_mods/LoganFraser/WagoMounts/CAD/Wago_3x_221-41x_Angled_Din_Rail_Mount.step
  printer_mods/LoganFraser/WagoMounts/README.md
  printer_mods/LoganFraser/WagoMounts/STLs/Din_Mount_Bracket.stl
  printer_mods/LoganFraser/WagoMounts/STLs/Wago-3x-221-413_Thin-Din_Rail_Mount.stl
  printer_mods/LoganFraser/WagoMounts/STLs/Wago_2x_221-415_Extrusion_Mount.stl
  printer_mods/LoganFraser/WagoMounts/STLs/Wago_2x_221-415_Thin_Din_Rail_Mount.stl
  printer_mods/LoganFraser/WagoMounts/STLs/Wago_3x_221-412_DIN_Mount.stl
  printer_mods/LoganFraser/WagoMounts/STLs/Wago_3x_221-413_DIN_Mount.stl
  printer_mods/LoganFraser/WagoMounts/STLs/Wago_3x_221-413_Extrusion_Mount.stl
  printer_mods/LoganFraser/WagoMounts/STLs/Wago_3x_221-415_DIN_Mount.stl
  printer_mods/LoganFraser/WagoMounts/STLs/Wago_3x_221-415_Extrusion_Mount.stl
  printer_mods/LoganFraser/WagoMounts/STLs/Wago_3x_221-415_Skirt_Inlet_Mount.stl
  printer_mods/LoganFraser/WagoMounts/STLs/Wago_3x_221-415_Thin_Din_Rail_Mount.stl
  printer_mods/LoganFraser/WagoMounts/STLs/Wago_4x_221-412_Extrusion_Mount.stl
  printer_mods/LoganFraser/WagoMounts/STLs/Wago_5x_221-412_Extrusion_Mount.stl
  printer_mods/LoganFraser/WagoMounts/WagoMounts-Extrusion&Din.png
  printer_mods/LoganFraser/WagoMounts/WagoMounts.png
  printer_mods/README.md
Labels: CR: Source Files

#686 Door panels
  printer_mods/README.md
  printer_mods/gamebofh/README.md
  printer_mods/gamebofh/door-panels/CAD/250mm-door-panel-holes.f3d
  printer_mods/gamebofh/door-panels/CAD/300mm-door-panel-holes.f3d
  printer_mods/gamebofh/door-panels/CAD/350mm-door-panel-holes.f3d
  printer_mods/gamebofh/door-panels/CAD/door-panel-holes.step
  printer_mods/gamebofh/door-panels/CAD/modified-door-latch.f3d
  printer_mods/gamebofh/door-panels/DXF/250mm-door-panel-holes.dxf
  printer_mods/gamebofh/door-panels/DXF/300mm-door-panel-holes.dxf
  printer_mods/gamebofh/door-panels/DXF/350mm-door-panel-holes.dxf
  printer_mods/gamebofh/door-panels/Images/door-fusion-screenshot.png
  printer_mods/gamebofh/door-panels/Images/door-hinge-installed.jpg
  printer_mods/gamebofh/door-panels/Images/door-hinge-lined-up.jpg
  printer_mods/gamebofh/door-panels/Images/door-latch-installed.jpg
  printer_mods/gamebofh/door-panels/README.md
  printer_mods/gamebofh/door-panels/STL/modified-door-latch.stl
Labels: CR: Readme, Pending Question

#628 Clip on door frame
  printer_mods/README.md
  printer_mods/scanlory/clip_on_door_frame/Images/door_latch.jpg
  printer_mods/scanlory/clip_on_door_frame/Images/full_front_view.jpg
  printer_mods/scanlory/clip_on_door_frame/Images/right_door.jpg
  printer_mods/scanlory/clip_on_door_frame/README.md
  printer_mods/scanlory/clip_on_door_frame/STLs/angle_frame_1_x2.stl
  printer_mods/scanlory/clip_on_door_frame/STLs/angle_frame_2_x2.stl
  printer_mods/scanlory/clip_on_door_frame/STLs/extended_door_latch_x2.stl
  printer_mods/scanlory/clip_on_door_frame/STLs/straight_frame_long_x2.stl
  printer_mods/scanlory/clip_on_door_frame/STLs/straight_frame_short_x4.stl
Labels: Ready to Merge

#676 3dpandme mods
  printer_mods/3dpandme/Fannypack_zero/Installed.jpg
  printer_mods/3dpandme/Fannypack_zero/README.md
  printer_mods/3dpandme/Fannypack_zero/back_panel_dxf.dxf
  printer_mods/3dpandme/Fannypack_zero/fannypack_zero.step
  printer_mods/3dpandme/Fannypack_zero/fannypack_zero.stl
  printer_mods/3dpandme/Thermistor_holder_zero/README.md
  printer_mods/3dpandme/Thermistor_holder_zero/installed.png
  printer_mods/3dpandme/Thermistor_holder_zero/thermistor_holder_comparison.png
  printer_mods/3dpandme/Thermistor_holder_zero/thermistor_holder_zero.step
  printer_mods/3dpandme/Thermistor_holder_zero/thermistor_holder_zero.stl
  printer_mods/README.md
Labels: Ready to Merge

#703 Adding Z Locks
  printer_mods/README.md
  printer_mods/tallman5/z-locks/cad/z-locks.f3d
  printer_mods/tallman5/z-locks/cad/z-locks.step
  printer_mods/tallman5/z-locks/images/z-locks-installed.png
  printer_mods/tallman5/z-locks/images/z-locks.png
  printer_mods/tallman5/z-locks/readme.md
  printer_mods/tallman5/z-locks/stls/z-locks-100.stl
  printer_mods/tallman5/z-locks/stls/z-locks-150.stl
  printer_mods/tallman5/z-locks/stls/z-locks-200.stl
Labels: Ready to Merge

#705 4.3 Fly Screen Mount
  printer_mods/README.md
  printer_mods/jaysuk/4.3_fly_screen_mount/CAD/4.3_fly_screen_mount.STEP
  printer_mods/jaysuk/4.3_fly_screen_mount/CAD/4.3_fly_screen_mount_assembly.STEP
  printer_mods/jaysuk/4.3_fly_screen_mount/Images/4.3_fly_screen_mount_assembly.JPG
  printer_mods/jaysuk/4.3_fly_screen_mount/STL/4.3_fly_screen_mount.STL
  printer_mods/jaysuk/4.3_fly_screen_mount/readme.md
Labels: Ready to Merge
