Repository VoronDesign/VoronUsers, pull requests merged in 2022-08, with the labels that each got.

#777 Adding my Switchwire mods. Side spool holder parts and panel jig.
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Mods/Switchwire/PTFE_tube_side_mount.step
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Mods/Switchwire/PTFE_tube_side_mount.stl
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Mods/Switchwire/README.md
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Mods/Switchwire/panel_spacer_tool.step
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Mods/Switchwire/panel_spacer_tool.stl
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Mods/Switchwire/spool_holder_base_side.step
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Mods/Switchwire/spool_holder_base_side.stl
Labels: Action required by maintainers

#642 Added Image
  printer_mods/MakeALeft/Switchwire_Front_Grill/Images/CleanGrill.jpg
  printer_mods/MakeALeft/Switchwire_Front_Grill/readme.md
  printer_mods/MakeALeft/Switchwire_Front_Grill/switchwire_front_grill.step
Labels: Action required by maintainers

#627 remove Spider DIN mount in favor of the Trident version
  printer_mods/geoffreyyoung/spider_bracket/README.md
  printer_mods/geoffreyyoung/spider_bracket/STLs/spider_bracket.stl
  printer_mods/geoffreyyoung/spider_bracket/images/spider_bracket.png
Labels: Action required by maintainers

#756 V0 Two Piece back panel with vents
  printer_mods/Polar-Ted/V0_Two_Piece_Back_Panel/Images/PXL_20220621_145343681.jpg
  printer_mods/Polar-Ted/V0_Two_Piece_Back_Panel/README.md
  printer_mods/Polar-Ted/V0_Two_Piece_Back_Panel/STEP/V0_1_Back_Panel_v7.step
  printer_mods/Polar-Ted/V0_Two_Piece_Back_Panel/STL/Back_Panel_Lower.stl
  printer_mods/Polar-Ted/V0_Two_Piece_Back_Panel/STL/Back_Panel_Upper.stl
  printer_mods/README.md
Labels: Ready to Merge

#767 Tool-free tensioner for Z-Axis on Voron 2.4
  printer_mods/Chaoticlab/Tool_free_tensioner/CAD/Tool_free_tensioner.STEP
  printer_mods/Chaoticlab/Tool_free_tensioner/Images/Tool_free_tensioner_1.png
  printer_mods/Chaoticlab/Tool_free_tensioner/Images/Tool_free_tensioner_2.png
  printer_mods/Chaoticlab/Tool_free_tensioner/README.md
  printer_mods/Chaoticlab/Tool_free_tensioner/STL/bracket.stl
  printer_mods/Chaoticlab/Tool_free_tensioner/STL/tensioner.stl
  printer_mods/Chaoticlab/Tool_free_tensioner/STL/wheel.stl
  printer_mods/README.md
Labels: Ready to Merge

#775 Reworked sketch to resolve in Fusion 360, re-exported
  printer_mods/richardjm/snap-latch-2020/CAD/NewLatch v108.f3d
  printer_mods/richardjm/snap-latch-2020/CAD/NewLatch-v106.f3d
  printer_mods/richardjm/snap-latch-2020/README.md
  printer_mods/richardjm/snap-latch-2020/STL/NewLatch-3.0mm.stl
  printer_mods/richardjm/snap-latch-2020/STL/NewLatch-3.5mm.stl
  printer_mods/richardjm/snap-latch-2020/STL/NewLatch-4.0mm.stl
  printer_mods/richardjm/snap-latch-2020/STL/NewLatch-4.5mm.stl
  printer_mods/richardjm/snap-latch-2020/STL/NewLatch-5.0mm.stl
  printer_mods/richardjm/snap-latch-2020/STL/NewLatch-5.5mm.stl
  printer_mods/richardjm/snap-latch-2020/STL/NewLatch-6.0mm.stl
  printer_mods/richardjm/snap-latch-2020/STL/NewLatch-6.5mm.stl
  printer_mods/richardjm/snap-latch-2020/STL/NewLatch-7.0mm.stl
  printer_mods/richardjm/snap-latch-2020/STL/NewLatch-7.5mm.stl
  printer_mods/richardjm/snap-latch-2020/STL/NewLatch-8.0mm.stl
  printer_mods/richardjm/snap-latch-2020/STL/NewLatch-8.5mm.stl
Labels: Action required by maintainers

#780 update readmed / add information about stealthburner umbilical cover
  printer_mods/Minsekt/Rear_Umbilical/README.md
Labels: Action required by maintainers

#781 Runout unklicky
  printer_mods/README.md
  printer_mods/chirpy/RunoutUnklicky/CAD/RunoutUnKlicky.step
  printer_mods/chirpy/RunoutUnklicky/README.md
  printer_mods/chirpy/RunoutUnklicky/STLs/Base.stl
  printer_mods/chirpy/RunoutUnklicky/STLs/Base_Collet.stl
  printer_mods/chirpy/RunoutUnklicky/STLs/Base_PC4-M6.stl
  printer_mods/chirpy/RunoutUnklicky/STLs/Pin.stl
  printer_mods/chirpy/RunoutUnklicky/STLs/Roller.stl
  printer_mods/chirpy/RunoutUnklicky/STLs/Top.stl
  printer_mods/chirpy/RunoutUnklicky/STLs/Top_1515.stl
  printer_mods/chirpy/RunoutUnklicky/STLs/Top_1515_NoNut.stl
  printer_mods/chirpy/RunoutUnklicky/STLs/Top_2020.stl
  printer_mods/chirpy/RunoutUnklicky/images/assembly.jpg
  printer_mods/chirpy/RunoutUnklicky/images/cable.jpg
  printer_mods/chirpy/RunoutUnklicky/images/designall.png
  printer_mods/chirpy/RunoutUnklicky/images/designtop.png
  printer_mods/chirpy/RunoutUnklicky/images/filament.jpg
  printer_mods/chirpy/RunoutUnklicky/images/magnets.jpg
  printer_mods/chirpy/RunoutUnklicky/images/nofilament.jpg
  printer_mods/chirpy/RunoutUnklicky/images/parts.jpg
  printer_mods/chirpy/RunoutUnklicky/images/pin.jpg
  printer_mods/chirpy/RunoutUnklicky/images/top.jpg
  printer_mods/chirpy/RunoutUnklicky/runoutunklicky.cfg
Labels: Action required by maintainers

#750 Slitte mods
  printer_mods/README.md
  printer_mods/slitte/PCB_Probe/Gerber/PCB_Probe_Gerber_Rev1.0.zip
  printer_mods/slitte/PCB_Probe/KiCad/PCB_Probe_Rev1.0.zip
  printer_mods/slitte/PCB_Probe/images/9C41BAE9-E4E5-412E-ABDE-0C47AB14D8F3.jpeg
  printer_mods/slitte/PCB_Probe/images/9FB91CEF-5DD7-4529-AA61-205C67A30F6B.jpeg
  printer_mods/slitte/PCB_Probe/images/D5D337EA-ACC4-4DDF-B353-550F60E1EAA6.jpeg
  printer_mods/slitte/PCB_Probe/readme.md
  printer_mods/slitte/ssd_bracket/STEP/ssd_bracket.step
  printer_mods/slitte/ssd_bracket/images/0354E8D1-312F-4349-B1D6-38239E54C75F.jpeg
  printer_mods/slitte/ssd_bracket/images/06C8B63A-0E93-41D4-B6F2-A8E8CFBC5BC6.jpeg
  printer_mods/slitte/ssd_bracket/images/A36AF599-317D-4D6E-8989-10924DDE9098.jpeg
  printer_mods/slitte/ssd_bracket/images/DEF912DF-37F4-4060-8EA9-BF4894C53D85.jpeg
  printer_mods/slitte/ssd_bracket/readme.md
  printer_mods/slitte/ssd_bracket/stl/ssd_bracket.stl
Labels: CR: STL Issues, Ready to Merge

#785 z idler corner cable cover with drop holes and inline hole cutouts
  printer_mods/Dr-Info/corner_cable_cover_with_drop_down_holes/CAD/top_corner_cable_cover_with_drop_holes.step
  printer_mods/Dr-Info/corner_cable_cover_with_drop_down_holes/Images/top_corner_cable_cover_with_drop_holes_bottom.JPG
  printer_mods/Dr-Info/corner_cable_cover_with_drop_down_holes/Images/top_corner_cable_cover_with_drop_holes_front.JPG
  printer_mods/Dr-Info/corner_cable_cover_with_drop_down_holes/Images/top_corner_cable_cover_with_drop_holes_installed.JPG
  printer_mods/Dr-Info/corner_cable_cover_with_drop_down_holes/README.md
  printer_mods/Dr-Info/corner_cable_cover_with_drop_down_holes/STL/top_corner_cable_cover_with_drop_holes.stl
  printer_mods/README.md
Labels: Ready to Merge

#800 Mandalaroseworks magnets avoidance
  firmware_configurations/README.md
  firmware_configurations/klipper/Mastah/mandalaRoseWorks_magnets_avoidance/images/bed_mesh.png
  firmware_configurations/klipper/Mastah/mandalaRoseWorks_magnets_avoidance/magnets_avoidance.txt
  firmware_configurations/klipper/Mastah/mandalaRoseWorks_magnets_avoidance/magnets_avoidance.xlsx
  firmware_configurations/klipper/Mastah/mandalaRoseWorks_magnets_avoidance/readme.md
Labels: Ready to Merge
