Repository VoronDesign/VoronUsers, pull requests merged in 2022-09, with the labels that each got.

#814 updated .dxf file
  printer_mods/3dpandme/Fannypack_zero/back_panel.dxf
Labels: Action required by maintainers

#786 Revo skirt nozzle holder
  printer_mods/README.md
  printer_mods/baccula/revo_skirt_nozzle_holder/CAD/revo_nozzle_holder.f3d
  printer_mods/baccula/revo_skirt_nozzle_holder/CAD/revo_nozzle_holder.step
  printer_mods/baccula/revo_skirt_nozzle_holder/Images/iso_closed.png
  printer_mods/baccula/revo_skirt_nozzle_holder/Images/iso_open.png
  printer_mods/baccula/revo_skirt_nozzle_holder/Images/print_closed.jpg
  printer_mods/baccula/revo_skirt_nozzle_holder/Images/print_open.jpg
  printer_mods/baccula/revo_skirt_nozzle_holder/README.md
  printer_mods/baccula/revo_skirt_nozzle_holder/STL/[a]_nozzle_holder.stl
  printer_mods/baccula/revo_skirt_nozzle_holder/STL/skirt_350.stl
Labels: Ready to Merge

#793 V0.1_Its_Not_a_Sexbolt_switch
  printer_mods/Polar-Ted/V0.1_Its_Not_a_Sexbolt_switch/README.MD
  printer_mods/Polar-Ted/V0.1_Its_Not_a_Sexbolt_switch/STEP/Its_Not_a_Sexbolt_z_Switch_v4.step
  printer_mods/Polar-Ted/V0.1_Its_Not_a_Sexbolt_switch/STL/Its_Not_a_Sexbolt_z_Switch_v4.stl
  printer_mods/Polar-Ted/V0.1_Its_Not_a_Sexbolt_switch/images/Dingushippo_magent1.jpg
  printer_mods/Polar-Ted/V0.1_Its_Not_a_Sexbolt_switch/images/Dingushippo_magent2.jpg
  printer_mods/Polar-Ted/V0.1_Its_Not_a_Sexbolt_switch/images/Dingushippo_plate.jpg
  printer_mods/Polar-Ted/V0.1_Its_Not_a_Sexbolt_switch/images/NotaSexboltimage.png
  printer_mods/README.md
Labels: CR: Readme
