Repository VoronDesign/VoronUsers, pull requests merged in 2022-03, with the labels that each got.

#604 Add LRS PSU screw terminal cover
  printer_mods/README.md
  printer_mods/samwiseg0/lrs_screw_terminal_cover/CAD/lrs_200_screw_terminal_cover.step
  printer_mods/samwiseg0/lrs_screw_terminal_cover/CAD/lrs_50_screw_terminal_cover.step
  printer_mods/samwiseg0/lrs_screw_terminal_cover/Images/lrs_200_screw_terminal_cover.png
  printer_mods/samwiseg0/lrs_screw_terminal_cover/Images/lrs_50_screw_terminal_cover.png
  printer_mods/samwiseg0/lrs_screw_terminal_cover/README.md
  printer_mods/samwiseg0/lrs_screw_terminal_cover/STLs/lrs_200_screw_terminal_cover.stl
  printer_mods/samwiseg0/lrs_screw_terminal_cover/STLs/lrs_50_screw_terminal_cover.stl
Labels: Ready to Merge

#542 Belts Holder for v0
  printer_mods/README.md
  printer_mods/TheSquiffy/V0_Belts_holder/Images/bh1.png
  printer_mods/TheSquiffy/V0_Belts_holder/Images/bh10.jpg
  printer_mods/TheSquiffy/V0_Belts_holder/Images/bh2.png
  printer_mods/TheSquiffy/V0_Belts_holder/Images/bh3.png
  printer_mods/TheSquiffy/V0_Belts_holder/Images/bh4.png
  printer_mods/TheSquiffy/V0_Belts_holder/Images/bh5.png
  printer_mods/TheSquiffy/V0_Belts_holder/Images/bh6.png
  printer_mods/TheSquiffy/V0_Belts_holder/Images/bh7.jpg
  printer_mods/TheSquiffy/V0_Belts_holder/Images/bh8.jpg
  printer_mods/TheSquiffy/V0_Belts_holder/Images/bh9.jpg
  printer_mods/TheSquiffy/V0_Belts_holder/Readme.md
  printer_mods/TheSquiffy/V0_Belts_holder/STL/belts_holder_bar_x2.stl
  printer_mods/TheSquiffy/V0_Belts_holder/STL/belts_holder_down_x1.stl
  printer_mods/TheSquiffy/V0_Belts_holder/STL/belts_holder_up_x1.stl
Labels: Action required by maintainers

#600 Add ab plug for gantry
  printer_mods/README.md
  printer_mods/samwiseg0/ab_plug_microfit_1x4/CAD/v24_ab_microfit_1x4.step
  printer_mods/samwiseg0/ab_plug_microfit_1x4/CAD/v24_ab_microfit_1x4_pme.step
  printer_mods/samwiseg0/ab_plug_microfit_1x4/Images/ab_microfit_1x4_non_pme.png
  printer_mods/samwiseg0/ab_plug_microfit_1x4/Images/ab_microfit_1x4_pme.png
  printer_mods/samwiseg0/ab_plug_microfit_1x4/README.md
  printer_mods/samwiseg0/ab_plug_microfit_1x4/STLs/ab_microfit_1x4/[a]_ab_microfit_1x4_side_1.stl
  printer_mods/samwiseg0/ab_plug_microfit_1x4/STLs/ab_microfit_1x4/[a]_ab_microfit_1x4_side_2.stl
  printer_mods/samwiseg0/ab_plug_microfit_1x4/STLs/ab_microfit_1x4_pme/[a]_ab_microfit_1x4_pme_side_1.stl
  printer_mods/samwiseg0/ab_plug_microfit_1x4/STLs/ab_microfit_1x4_pme/[a]_ab_microfit_1x4_pme_side_2.stl
Labels: CR: Readme

#657 More robust belt paths for Voron Switchwire
  printer_mods/README.md
  printer_mods/yenda/vsw_more_robust_belt_paths/cad/motor_mounts v1.f3d
  printer_mods/yenda/vsw_more_robust_belt_paths/cad/upper_xz v6.f3d
  printer_mods/yenda/vsw_more_robust_belt_paths/cad/xz blocks v3.f3d
  printer_mods/yenda/vsw_more_robust_belt_paths/images/install_cage_a.jpg
  printer_mods/yenda/vsw_more_robust_belt_paths/images/install_cage_b.jpg
  printer_mods/yenda/vsw_more_robust_belt_paths/images/install_upper_xz_blocks.jpg
  printer_mods/yenda/vsw_more_robust_belt_paths/images/install_xz_blocks.jpg
  printer_mods/yenda/vsw_more_robust_belt_paths/images/motor_cage.png
  printer_mods/yenda/vsw_more_robust_belt_paths/images/upper_xz.png
  printer_mods/yenda/vsw_more_robust_belt_paths/images/xz_blocks.png
  printer_mods/yenda/vsw_more_robust_belt_paths/readme.md
  printer_mods/yenda/vsw_more_robust_belt_paths/stl/[a]_upper_idler_support_b_left_x1.stl
  printer_mods/yenda/vsw_more_robust_belt_paths/stl/[a]_upper_idler_support_b_right_x1.stl
  printer_mods/yenda/vsw_more_robust_belt_paths/stl/x_motor_mount_a_x1.stl
  printer_mods/yenda/vsw_more_robust_belt_paths/stl/x_motor_mount_b_x1.stl
  printer_mods/yenda/vsw_more_robust_belt_paths/stl/xz_block_left_a_x1.stl
  printer_mods/yenda/vsw_more_robust_belt_paths/stl/xz_block_left_b_x1.stl
  printer_mods/yenda/vsw_more_robust_belt_paths/stl/xz_block_right_a_x1.stl
  printer_mods/yenda/vsw_more_robust_belt_paths/stl/xz_block_right_b_x1.stl
  printer_mods/yenda/vsw_more_robust_belt_paths/stl/z_motor_mount_a_x1.stl
  printer_mods/yenda/vsw_more_robust_belt_paths/stl/z_motor_mount_b_x1.stl
Labels: Ready to Merge

#655 CR Touch Probe "Snap Mount" for v2.4 (MGN9)
  printer_mods/JJFX/CRTouch_Snap_Mount/CRTouch-mount.stl
  printer_mods/JJFX/CRTouch_Snap_Mount/CRTouch-spacer.stl
  printer_mods/JJFX/CRTouch_Snap_Mount/Images/CRTouch-Front_sm.JPG
  printer_mods/JJFX/CRTouch_Snap_Mount/Images/CRTouch-b1_explode_sm.JPG
  printer_mods/JJFX/CRTouch_Snap_Mount/Images/CRTouch-b1_install1_sm.JPG
  printer_mods/JJFX/CRTouch_Snap_Mount/Images/CRTouch-b1_install2_sm.JPG
  printer_mods/JJFX/CRTouch_Snap_Mount/Images/CRTouch-ex1_sm.jpg
  printer_mods/JJFX/CRTouch_Snap_Mount/Images/CRTouch-ex2_sm.jpg
  printer_mods/JJFX/CRTouch_Snap_Mount/Images/CRTouch-ex3_sm.jpg
  printer_mods/JJFX/CRTouch_Snap_Mount/Images/CRTouch-rear2_sm.JPG
  printer_mods/JJFX/CRTouch_Snap_Mount/Images/CRTouch-wire1_sm.jpg
  printer_mods/JJFX/CRTouch_Snap_Mount/Images/CRTouch_Inserts1_sm.jpg
  printer_mods/JJFX/CRTouch_Snap_Mount/Images/CRTouch_Prep0_sm.jpg
  printer_mods/JJFX/CRTouch_Snap_Mount/Images/CRTouch_Prep1_sm.jpg
  printer_mods/JJFX/CRTouch_Snap_Mount/Images/CRTouch_Prep3_sm.jpg
  printer_mods/JJFX/CRTouch_Snap_Mount/LICENSE
  printer_mods/JJFX/CRTouch_Snap_Mount/README.md
  printer_mods/JJFX/README.md
  printer_mods/README.md
Labels: Ready to Merge

#633 Adding Kirigami bed led front
  printer_mods/README.md
  printer_mods/reQu1em00/Kirigami_LED_Bed_Front/Kirigami_Bed_LED_Diffuser .stl
  printer_mods/reQu1em00/Kirigami_LED_Bed_Front/Kirigami_Bed_LED_Front.stl
  printer_mods/reQu1em00/Kirigami_LED_Bed_Front/README.md
Labels: CR: STL Issues, Ready to Merge

#626 Add sample printer.cfg for Fysetc Spider 2.2 for Voron Trident
  firmware_configurations/README.md
  firmware_configurations/klipper/redelman/Spider_2.2_Voron_Trident/Trident_Spider_2_2.cfg
Labels: CR: Files and Folders

#652 Revo Voron Added
  printer_mods/Badnoob/ABBN_for_Stock/CAD/RevoVoron_AB_4020.step
  printer_mods/Badnoob/ABBN_for_Stock/Readme.md
  printer_mods/Badnoob/ABBN_for_Stock/STLs/ABBN_4020_REVO_Voron_Back.stl
  printer_mods/Badnoob/ABBN_for_Stock/STLs/ABBN_4020_REVO_Voron_Front.stl
Labels: CR: STL Issues
