Repository VoronDesign/VoronUsers, pull requests merged in 2022-01, with the labels that each got.

#575 Fixed hole in FrontBottom-Bracket.stl for better printing
  printer_mods/MathematicalPotato/v0.1_belted_z_drive/STL/V0-ZBelt-FrontBottom-Bracket.stl
Labels: Pending Question

#531 Adding mod
  printer_mods/JeremyRuhland/V2.4_Plug_Panel_Generic_Combo/README.md
  printer_mods/JeremyRuhland/V2.4_Plug_Panel_Generic_Combo/cad/plug_panel_generic_combo.f3d
  printer_mods/JeremyRuhland/V2.4_Plug_Panel_Generic_Combo/img/AC19A10-G8.jpg
  printer_mods/JeremyRuhland/V2.4_Plug_Panel_Generic_Combo/img/plug_panel.jpg
  printer_mods/JeremyRuhland/V2.4_Plug_Panel_Generic_Combo/img/plug_panel_generic_combo.jpg
  printer_mods/JeremyRuhland/V2.4_Plug_Panel_Generic_Combo/stl/plug_panel_generic_combo.stl
  printer_mods/README.md
Labels: Ready to Merge

#571 Power Inlet w Keystone Insert Slot for v0.1
  printer_mods/Polared/Power_Inlet_w_Keystone_Insert/STLs/Power_Inlet_w_Keystone_Insert_x1.stl
  printer_mods/Polared/Power_Inlet_w_Keystone_Insert/images/installed.jpg
  printer_mods/Polared/Power_Inlet_w_Keystone_Insert/readme.md
  printer_mods/README.md
Labels: Ready to Merge

#566 Add Cable Management Duct
  printer_mods/README.md
  printer_mods/ryandam/Cable_management_duct/Images/VORON_V0.1_cable_management_duct.png
  printer_mods/ryandam/Cable_management_duct/Images/VORON_V0.1_cable_management_duct_flat.png
  printer_mods/ryandam/Cable_management_duct/README.md
  printer_mods/ryandam/Cable_management_duct/STEP/VoronV0_CableManagementDuct.step
  printer_mods/ryandam/Cable_management_duct/STLs/CableDuctBody.stl
  printer_mods/ryandam/Cable_management_duct/STLs/CableDuctBody_small.stl
  printer_mods/ryandam/Cable_management_duct/STLs/CableDuctCover.stl
  printer_mods/ryandam/Cable_management_duct/STLs/CableDuctCover_nologo_small.stl
  printer_mods/ryandam/Cable_management_duct/STLs/CableDuctCover_small.stl
Labels: Ready to Merge

#574 Initial pull request for BTT SKR v2 config
  firmware_configurations/README.md
  firmware_configurations/klipper/TechnoPhreak/BTT_SKR_v2/Klipper-menuconfig.png
  firmware_configurations/klipper/TechnoPhreak/BTT_SKR_v2/README.md
  firmware_configurations/klipper/TechnoPhreak/BTT_SKR_v2/SKR2-MCUXYE-wiring.jpg
  firmware_configurations/klipper/TechnoPhreak/BTT_SKR_v2/SKR2-MCUZ-wiring.jpg
  firmware_configurations/klipper/TechnoPhreak/BTT_SKR_v2/printer.cfg
Labels: Ready to Merge

#563 LGX_Lite
  printer_mods/Mrgl-Mrgl/LGX_Lite_Mount/LGXLite_Mount.stl
  printer_mods/Mrgl-Mrgl/LGX_Lite_Mount/LGX_Lite_Chainmount_Generic.stl
  printer_mods/Mrgl-Mrgl/LGX_Lite_Mount/LGX_Lite_Chainmount_IGUS.stl
  printer_mods/Mrgl-Mrgl/LGX_Lite_Mount/Lgx_Lite_Mounting.png
  printer_mods/Mrgl-Mrgl/LGX_Lite_Mount/README.md
  printer_mods/README.md
Labels: Ready to Merge

#581 V0.1 Spool Holder using Side Panel Clips
  printer_mods/BladeScraper-Designs/CornerPanel_SpoolHolder/CAD/CornerPanel/CornerPanel_2.5mm.stp
  printer_mods/BladeScraper-Designs/CornerPanel_SpoolHolder/CAD/CornerPanel/CornerPanel_2mm.stp
  printer_mods/BladeScraper-Designs/CornerPanel_SpoolHolder/CAD/CornerPanel/CornerPanel_3.25mm.stp
  printer_mods/BladeScraper-Designs/CornerPanel_SpoolHolder/CAD/CornerPanel/CornerPanel_3mm.stp
  printer_mods/BladeScraper-Designs/CornerPanel_SpoolHolder/CAD/SpoolHolder.stp
  printer_mods/BladeScraper-Designs/CornerPanel_SpoolHolder/IMG/Cornerpanel_Spoolholder.png
  printer_mods/BladeScraper-Designs/CornerPanel_SpoolHolder/IMG/Extrude_This.png
  printer_mods/BladeScraper-Designs/CornerPanel_SpoolHolder/IMG/IRL.jpg
  printer_mods/BladeScraper-Designs/CornerPanel_SpoolHolder/STL/CornerPanel/CornerPanel_2.5mm.stl
  printer_mods/BladeScraper-Designs/CornerPanel_SpoolHolder/STL/CornerPanel/CornerPanel_2mm.stl
  printer_mods/BladeScraper-Designs/CornerPanel_SpoolHolder/STL/CornerPanel/CornerPanel_3.25mm.stl
  printer_mods/BladeScraper-Designs/CornerPanel_SpoolHolder/STL/CornerPanel/CornerPanel_3mm.stl
  printer_mods/BladeScraper-Designs/CornerPanel_SpoolHolder/STL/SpoolHolder.stl
  printer_mods/BladeScraper-Designs/CornerPanel_SpoolHolder/readme.md
  printer_mods/README.md
Labels: CR: STL Issues

#587 Adding an area to share the various Parts, Jigs and Mods that I use.
  printer_mods/README.md
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Mods/Legacy_Ender3_bed_mount_A_x2.stl
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Mods/Legacy_Ender3_bed_mount_B_x2.stl
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Parts/6-pin_microfit_skirt_insert.stl
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Parts/README.md
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Parts/WAGO_221-412_mount-3x2.stl
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Parts/WAGO_221-415_mount-3x5_90.stl
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Parts/ZipTie_Anchor.stl
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/README.md
  printer_mods/StvPtrsn/Parts_Jigs_and_Mods/Tools_Jigs/PTFE_Flush_Cutter.stl
Labels: CR: Readme, CR: STL Issues

#570 Switchwire Clean Front Middle Grill
  printer_mods/MakeALeft/Switchwire_Front_Grill/front_mid_grill_no_magnets.stl
  printer_mods/MakeALeft/Switchwire_Front_Grill/readme.md
  printer_mods/README.md
Labels: Ready to Merge

#562 Add Raspberry Pi Zero Bracket to printer_mods
  printer_mods/D4rkCelerity/Raspberry_Pi_Zero_Bracket/README.md
  printer_mods/D4rkCelerity/Raspberry_Pi_Zero_Bracket/STL/raspberrypi_zero_bracket.stl
  printer_mods/D4rkCelerity/Raspberry_Pi_Zero_Bracket/image/Rendering.JPG
  printer_mods/README.md
Labels: Ready to Merge

#521 V0 skirt, add Adxl connector
  printer_mods/README.md
  printer_mods/Zen3D/V0_Skirt/IMG/img9.jpg
  printer_mods/Zen3D/V0_Skirt/README.md
  printer_mods/Zen3D/V0_Skirt/V0.0/Skirt.stl
  printer_mods/Zen3D/V0_Skirt/V0.0/Skirt_EmptyNameplate.stl
  printer_mods/Zen3D/V0_Skirt/V0.0/Skirt_PowerSwitch.stl
  printer_mods/Zen3D/V0_Skirt/V0.0/Skirt_adxl.stl
  printer_mods/Zen3D/V0_Skirt/V0.0/Skirt_mirror.stl
  printer_mods/Zen3D/V0_Skirt/V0.0/Skirt_ssr.stl
  printer_mods/Zen3D/V0_Skirt/V0.1/Skirt.stl
  printer_mods/Zen3D/V0_Skirt/V0.1/Skirt_mirror.stl
Labels: CR: Readme

#550 Exhaust Adapter for 100mm ventilation systems
  printer_mods/README.md
  printer_mods/chri.kai.in/Exhaust_Adapter_100mm/CAD/VORON2_v2.4_Exhaust_Adapter_100mm_RC3.step
  printer_mods/chri.kai.in/Exhaust_Adapter_100mm/Images/Exhaust_Adapter_ISO.png
  printer_mods/chri.kai.in/Exhaust_Adapter_100mm/Images/Exhaust_Adapter_ISO_rendered_bright.png
  printer_mods/chri.kai.in/Exhaust_Adapter_100mm/Images/Exhaust_Adapter_sideview.png
  printer_mods/chri.kai.in/Exhaust_Adapter_100mm/ReadMe.md
  printer_mods/chri.kai.in/Exhaust_Adapter_100mm/STL/VORON2_v2.4_Exhaust_Adapter_100mm_RC3.stl
Labels: Ready to Merge

#592 Update readme.md: Notes about Igus EGLM vs KGLM
  printer_mods/hartk1213/Voron2.4_GE5C/readme.md
Labels: Ready to Merge
